HOMEPAGE = 'homepage'
WORKBOEK = 'workboek'
WORKGROEP = 'workgroep'
COMMON = 'common'

COMMON_CONTACT_US_EMAIL = COMMON + '_contact_us_email'
COMMON_CONTACT_US_PHONE = COMMON + '_contact_us_phone'
COMMON_SOCIAL_TWITTER = COMMON + '_social_twitter'
COMMON_SOCIAL_FACEBOOK = COMMON + '_social_facebook'
COMMON_SOCIAL_LINKEDIN = COMMON + '_social_linkedin'
COMMON_SOCIAL_YOUTUBE = COMMON + '_social_youtube'

HOMEPAGE_MAIN_TITLE = HOMEPAGE + '_main_title'
HOMEPAGE_MAIN_TEXT = HOMEPAGE + '_main_text'
HOMEPAGE_MAIN_PHOTO = HOMEPAGE + '_main_photo'
HOMEPAGE_ABOUT_TITLE = HOMEPAGE + '_about_title'
HOMEPAGE_ABOUT_TEXT = HOMEPAGE + '_about_text'
HOMEPAGE_ABOUT_PHOTO = HOMEPAGE + '_about_photo'
HOMEPAGE_ABOUT_VIDEO = HOMEPAGE + '_about_video'

WORKBOEK_MAIN_TITLE = WORKBOEK + '_main_title'
WORKBOEK_MAIN_TEXT = WORKBOEK + '_main_text'

WORKGROEP_FIRST_DOCUMENT_TITLE = WORKGROEP + '_first_document_title'
WORKGROEP_FIRST_DOCUMENT_FILE = WORKGROEP + '_first_document_file'
WORKGROEP_SECOND_DOCUMENT_TITLE = WORKGROEP + '_second_document_title'
WORKGROEP_SECOND_DOCUMENT_FILE = WORKGROEP + '_second_document_file'
WORKGROEP_CONTACT_US_TITLE = WORKGROEP + '_contact_us_title'
WORKGROEP_CONTACT_US_TEXT = WORKGROEP + '_contact_us_text'

CONTENT_NAMES = (
    (COMMON_CONTACT_US_EMAIL, COMMON_CONTACT_US_EMAIL),
    (COMMON_CONTACT_US_PHONE, COMMON_CONTACT_US_PHONE),
    (COMMON_SOCIAL_TWITTER, COMMON_SOCIAL_TWITTER),
    (COMMON_SOCIAL_FACEBOOK, COMMON_SOCIAL_FACEBOOK),
    (COMMON_SOCIAL_LINKEDIN, COMMON_SOCIAL_LINKEDIN),
    (COMMON_SOCIAL_YOUTUBE, COMMON_SOCIAL_YOUTUBE),
    (HOMEPAGE_MAIN_TITLE, HOMEPAGE_MAIN_TITLE),
    (HOMEPAGE_MAIN_TEXT, HOMEPAGE_MAIN_TEXT),
    (HOMEPAGE_MAIN_PHOTO, HOMEPAGE_MAIN_PHOTO),
    (HOMEPAGE_ABOUT_TITLE, HOMEPAGE_ABOUT_TITLE),
    (HOMEPAGE_ABOUT_TEXT, HOMEPAGE_ABOUT_TEXT),
    (HOMEPAGE_ABOUT_PHOTO, HOMEPAGE_ABOUT_PHOTO),
    (HOMEPAGE_ABOUT_VIDEO, HOMEPAGE_ABOUT_VIDEO),
    (WORKBOEK_MAIN_TITLE, WORKBOEK_MAIN_TITLE),
    (WORKBOEK_MAIN_TEXT, WORKBOEK_MAIN_TEXT),
    (WORKGROEP_FIRST_DOCUMENT_TITLE, WORKGROEP_FIRST_DOCUMENT_TITLE),
    (WORKGROEP_FIRST_DOCUMENT_FILE, WORKGROEP_FIRST_DOCUMENT_FILE),
    (WORKGROEP_SECOND_DOCUMENT_TITLE, WORKGROEP_SECOND_DOCUMENT_TITLE),
    (WORKGROEP_SECOND_DOCUMENT_FILE, WORKGROEP_SECOND_DOCUMENT_FILE),
    (WORKGROEP_CONTACT_US_TITLE, WORKGROEP_CONTACT_US_TITLE),
    (WORKGROEP_CONTACT_US_TEXT, WORKGROEP_CONTACT_US_TEXT),
)

CONTENT_MAP = {
    HOMEPAGE: [
        HOMEPAGE_MAIN_TITLE,
        HOMEPAGE_MAIN_TEXT,
        HOMEPAGE_MAIN_PHOTO,
        HOMEPAGE_ABOUT_TITLE,
        HOMEPAGE_ABOUT_TEXT,
        HOMEPAGE_ABOUT_PHOTO,
        HOMEPAGE_ABOUT_VIDEO,
    ],
    WORKBOEK: [
        WORKBOEK_MAIN_TITLE,
        WORKBOEK_MAIN_TEXT,
    ],
    WORKGROEP: [
        WORKGROEP_FIRST_DOCUMENT_TITLE,
        WORKGROEP_FIRST_DOCUMENT_FILE,
        WORKGROEP_SECOND_DOCUMENT_TITLE,
        WORKGROEP_SECOND_DOCUMENT_FILE,
        WORKGROEP_CONTACT_US_TITLE,
        WORKGROEP_CONTACT_US_TEXT,
    ],
    COMMON: [
        COMMON_CONTACT_US_EMAIL,
        COMMON_CONTACT_US_PHONE,
        COMMON_SOCIAL_TWITTER,
        COMMON_SOCIAL_FACEBOOK,
        COMMON_SOCIAL_LINKEDIN,
        COMMON_SOCIAL_YOUTUBE,
    ],
}
