# Generated by Django 2.0 on 2018-02-14 15:51

from django.db import migrations


def create_admin(apps, schema_editor):
    from django.contrib.auth import get_user_model
    from django.conf import settings
    admin_data = settings.INITIAL_ADMIN
    get_user_model().objects.create_admin(**admin_data)


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
