# Generated by Django 2.0 on 2017-12-26 16:57

from django.db import migrations


def create_admin(apps, schema_editor):
    from academy.src.academy_site.models import AuthUser
    from django.conf import settings
    admin_data = settings.INITIAL_ADMIN
    AuthUser.objects.create_admin(**admin_data)


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
