# Generated by Django 2.0 on 2018-02-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0002_auto_20180214_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='salutation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
