# Generated by Django 2.0 on 2017-12-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0003_siteuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'contact us',
                'verbose_name_plural': 'contacts us',
                'db_table': 'contact_us',
            },
        ),
    ]
