# Generated by Django 2.0 on 2018-02-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0003_siteuser_salutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='video',
            field=models.URLField(default='http://127.0.0.1:8000/admin/courses/'),
            preserve_default=False,
        ),
    ]
