# Generated by Django 2.0 on 2018-01-10 17:05

import academy_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0004_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=academy_site.models.get_city_photo_path)),
                ('school_address', models.CharField(max_length=100)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('logo', models.ImageField(upload_to=academy_site.models.get_partner_logo_path)),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
                'db_table': 'partner',
            },
        ),
        migrations.AlterField(
            model_name='authuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=academy_site.models.get_user_photo_path),
        ),
        migrations.AddField(
            model_name='city',
            name='partner',
            field=models.ManyToManyField(to='academy_site.Partner'),
        ),
    ]
