# Generated by Django 2.0 on 2018-02-20 10:27

import academy_site.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0004_city_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=academy_site.models.get_city_photo_path),
        ),
        migrations.AlterField(
            model_name='city',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
