# Generated by Django 2.0 on 2018-01-15 21:31

import academy_site.models
import academy_site.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0005_auto_20180110_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('practise_info', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_description', models.CharField(blank=True, max_length=100, null=True)),
                ('seats', models.IntegerField(validators=[academy_site.validators.positive_number])),
                ('remaining_seats', models.IntegerField(blank=True, validators=[academy_site.validators.positive_number])),
                ('status', models.CharField(choices=[('planned', 'planned'), ('available', 'available'), ('cancelled', 'cancelled'), ('sold-out', 'sold-out'), ('archived', 'archived')], max_length=10)),
                ('partner', models.ManyToManyField(to='academy_site.Partner')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'db_table': 'lesson',
            },
        ),
        migrations.CreateModel(
            name='LessonDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_site.Lesson')),
            ],
            options={
                'verbose_name': 'lesson date',
                'verbose_name_plural': 'lesson dates',
                'db_table': 'lesson_date',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=academy_site.models.get_theme_photo_path)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_site.City')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('know_academy_through', models.CharField(blank=True, max_length=100, null=True)),
                ('questions', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_site.Lesson')),
            ],
            options={
                'verbose_name': 'user lesson',
                'verbose_name_plural': 'user lessons',
                'db_table': 'user_lesson',
            },
        ),
        migrations.RenameField(
            model_name='siteuser',
            old_name='user',
            new_name='auth_user',
        ),
        migrations.AddField(
            model_name='userlesson',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_site.SiteUser'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_site.Theme'),
        ),
    ]
