# Generated by Django 2.0 on 2018-02-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0006_auto_20180220_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='know_academy_through',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
