# Generated by Django 2.0 on 2018-01-22 11:54

import academy_site.validators
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0006_auto_20180115_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('practise_info', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_description', models.CharField(blank=True, max_length=100, null=True)),
                ('seats', models.IntegerField(validators=[academy_site.validators.positive_number])),
                ('remaining_seats', models.IntegerField(blank=True, validators=[academy_site.validators.positive_number])),
                ('status', models.CharField(choices=[('planned', 'planned'), ('available', 'available'), ('cancelled', 'cancelled'), ('sold-out', 'sold-out'), ('archived', 'archived')], max_length=10)),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('other_link', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'teacher',
                'verbose_name_plural': 'teachers',
                'db_table': 'teacher',
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('know_academy_through', models.CharField(blank=True, max_length=100, null=True)),
                ('questions', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_site.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_site.SiteUser')),
            ],
            options={
                'verbose_name': 'user course',
                'verbose_name_plural': 'user courses',
                'db_table': 'user_course',
            },
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
        migrations.RemoveField(
            model_name='lessondate',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='userlesson',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'permissions': (('some_perm', 'custom permission'),), 'verbose_name': 'authenticated user', 'verbose_name_plural': 'authenticated users'},
        ),
        migrations.RenameField(
            model_name='city',
            old_name='partner',
            new_name='partners',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='location',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='name',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='practise_info',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='price_description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='remaining_seats',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='theme',
        ),
        migrations.AddField(
            model_name='authuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy_site.City'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 22, 11, 54, 31, 473299, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='partners',
            field=models.ManyToManyField(to='academy_site.Partner'),
        ),
        migrations.DeleteModel(
            name='LessonDate',
        ),
        migrations.DeleteModel(
            name='UserLesson',
        ),
        migrations.AddField(
            model_name='teacher',
            name='auth_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='partners',
            field=models.ManyToManyField(to='academy_site.Partner'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='academy_site.Teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy_site.Theme'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy_site.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteuser',
            name='courses',
            field=models.ManyToManyField(through='academy_site.UserCourse', to='academy_site.Course'),
        ),
    ]
