# Generated by Django 2.0 on 2018-02-21 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0007_usercourse_know_academy_through'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('mother_language', models.CharField(max_length=50)),
                ('salutation', models.CharField(max_length=50)),
                ('know_academy_through', models.CharField(max_length=200)),
                ('postcode', models.IntegerField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('confirmation_code', models.CharField(max_length=64)),
                ('confirmation_code_expires', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'anonymous',
                'verbose_name_plural': 'anonymous',
                'db_table': 'anonymous',
            },
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='know_academy_through',
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='questions',
            field=models.CharField(default='qqq', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy_site.SiteUser'),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='anonymous',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy_site.Anonymous'),
        ),
    ]
