# Generated by Django 2.0 on 2018-01-29 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0008_auto_20180124_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
