# Generated by Django 2.0 on 2018-02-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0009_auto_20180221_0953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('theme', 'slug'), ('theme', 'name')},
        ),
    ]
