# Generated by Django 2.0 on 2018-02-04 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0009_teacher_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
