# Generated by Django 2.0 on 2018-02-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0010_theme_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
