# Generated by Django 2.0 on 2018-02-21 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0010_auto_20180221_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymous',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='anonymous',
            name='confirmation_code_expires',
        ),
        migrations.RemoveField(
            model_name='anonymous',
            name='is_confirmed',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='confirmation_code',
            field=models.CharField(default='qqq', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercourse',
            name='confirmation_code_expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercourse',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
