# Generated by Django 2.0 on 2018-02-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0011_auto_20180221_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='rate',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usercourse',
            name='vote',
            field=models.SmallIntegerField(choices=[(-1, 'Dislike'), (1, 'Like')], default=0),
        ),
    ]
