# Generated by Django 2.0 on 2018-02-05 12:07

import academy_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0011_theme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=academy_site.models.get_course_photo_path),
        ),
    ]
