# Generated by Django 2.0 on 2018-02-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0012_auto_20180222_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='remaining_seats',
        ),
    ]
