# Generated by Django 2.0 on 2018-02-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0013_auto_20180205_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
