# Generated by Django 2.0 on 2018-02-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0013_remove_course_remaining_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='is_unsubscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('planned', 'planned'), ('available', 'available'), ('cancelled', 'cancelled'), ('archived', 'archived')], max_length=10),
        ),
    ]
