# Generated by Django 2.0 on 2018-02-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0014_auto_20180222_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('planned', 'planned'), ('available', 'available'), ('cancelled', 'cancelled')], max_length=10),
        ),
    ]
