# Generated by Django 2.0 on 2018-02-06 11:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0014_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usercourse',
            unique_together={('user', 'course')},
        ),
    ]
