# Generated by Django 2.0 on 2018-02-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0015_auto_20180206_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
