# Generated by Django 2.0 on 2018-02-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0016_siteuser_is_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='is_guest',
        ),
    ]
