# Generated by Django 2.0 on 2018-02-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0017_remove_siteuser_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
