# Generated by Django 2.0 on 2018-02-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0018_auto_20180208_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='mother_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
