# Generated by Django 2.0 on 2018-02-09 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0019_usercourse_mother_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='confirmation_code',
            field=models.CharField(default='qwer', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteuser',
            name='confirmation_code_expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteuser',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
