# Generated by Django 2.0 on 2018-02-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy_site', '0020_auto_20180209_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='confirmation_code',
            field=models.CharField(max_length=64),
        ),
    ]
