# Generated by Django 2.0 on 2018-03-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_name', models.CharField(choices=[('homepage_main_title', 'homepage_main_title'), ('homepage_main_text', 'homepage_main_text'), ('homepage_main_photo', 'homepage_main_photo'), ('homepage_about_title', 'homepage_about_title'), ('homepage_about_text', 'homepage_about_text'), ('homepage_about_photo', 'homepage_about_photo'), ('homepage_about_video', 'homepage_about_video'), ('homepage_contact_us_email', 'homepage_contact_us_email'), ('homepage_contact_us_phone', 'homepage_contact_us_phone'), ('homepage_social_facebook', 'homepage_social_facebook'), ('workboek_main_title', 'workboek_main_title'), ('workboek_main_text', 'workboek_main_text'), ('workgroep_first_document_title', 'workgroep_first_document_title'), ('workgroep_first_document_file', 'workgroep_first_document_file'), ('workgroep_second_document_title', 'workgroep_second_document_title'), ('workgroep_second_document_file', 'workgroep_second_document_file'), ('workgroep_contact_us_title', 'workgroep_contact_us_title'), ('workgroep_contact_us_text', 'workgroep_contact_us_text')], max_length=50)),
                ('data', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'content',
                'verbose_name_plural': 'content',
                'db_table': 'content',
            },
        ),
    ]
