# Generated by Django 2.0 on 2018-03-05 10:59

from django.db import migrations


def initial_content(apps, schema_editor):
    from academy_admin.models import Content
    from academy_admin.choices import CONTENT_NAMES
    content_list = [name[0] for name in CONTENT_NAMES]
    content_instances = [Content(personal_name=content_name) for content_name in content_list]
    Content.objects.bulk_create(content_instances)


class Migration(migrations.Migration):

    dependencies = [
        ('academy_admin', '0002_auto_20180305_1058'),
    ]

    operations = [
        migrations.RunPython(initial_content),
    ]
