PLANNED = 'planned'
AVAILABLE = 'available'
CANCELLED = 'cancelled'
SOLD_OUT = 'sold-out'
ARCHIVED = 'archived'

STATUS_CHOICES = (
    (PLANNED, PLANNED),
    (AVAILABLE, AVAILABLE),
    (CANCELLED, CANCELLED),
)

ADMINISTRATOR = 'Administrator'
MODERATOR = 'Moderator'
TEACHER = 'Teacher'
SITE_USER = 'Site user'

ADMIN_ROLE_CHOICES = (
    (ADMINISTRATOR, ADMINISTRATOR),
    (MODERATOR, MODERATOR),
)

BACKOFFICE_ROLE_CHOICES = (
    (ADMINISTRATOR, ADMINISTRATOR),
    (MODERATOR, MODERATOR),
    (TEACHER, TEACHER),
)
